language: c

compiler:
  - clang
  - gcc

notifications:
  email: false

before_install:
  - sudo apt-get install -qq cstream

before_script:
  - "make"
  - "sudo make install"

script:
  - "make test"
